# Currently Unused:
#parameters:
#    database_host:      127.0.0.1
#    database_port:      3306
#    database_name:      db_name
#    database_user:      db_user
#    database_password:  db_password
